# Generated by Django 3.2.23 on 2024-01-25 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='event',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='direction',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_directions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
