# Generated by Django 4.2.10 on 2024-04-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_participant', models.PositiveIntegerField(default=0, verbose_name='Общее количество участников')),
                ('total_number_of_participants_who_completed_event', models.PositiveIntegerField(default=0, verbose_name='Общее количество участников, завершивших событие')),
                ('total_number_of_completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Общее количество решённых заданий')),
                ('total_number_of_completed_exp', models.PositiveIntegerField(default=0, verbose_name='Общее количество полученного опыта')),
                ('total_number_of_participant_points', models.PositiveIntegerField(default=0, verbose_name='Общее количество полученных очков')),
            ],
            options={
                'verbose_name': 'Статистика события',
                'verbose_name_plural': 'Статистики событий',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Титульник')),
                ('needed_exp', models.PositiveIntegerField(verbose_name='Необходимое количество опыта')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('completed_events', models.ManyToManyField(blank=True, default=None, to='Event.event', verbose_name='Завершённые события')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Statistic.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистики пользователей',
            },
        ),
    ]
