# Generated by Django 4.2.10 on 2024-03-05 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='programming_languages', verbose_name='Иконка')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Заголовок')),
                ('condition', models.TextField(verbose_name='Условие')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('answer_structure', models.TextField(blank=True, default='#Введите ваш код здесь', verbose_name='Структура ответа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.event', verbose_name='Событие')),
                ('programming_languages', models.ManyToManyField(to='Task.programminglanguage', verbose_name='Доступные языки')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Входные данные')),
                ('output_data', models.TextField(verbose_name='Выходные данные')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Тестовые данные',
                'verbose_name_plural': 'Тестовые данные',
            },
        ),
        migrations.CreateModel(
            name='TaskReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponts', models.PositiveIntegerField(verbose_name='Поинты')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Task.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Награда за задание',
                'verbose_name_plural': 'Награды за задания',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Комментарий к заданию',
                'verbose_name_plural': 'Комментарии к заданям',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Результат')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильность')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
